# Generated by Django 2.2.5 on 2020-03-05 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCounters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('counter', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gsttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=150)),
                ('igst', models.BooleanField()),
                ('cgst', models.BooleanField()),
                ('sgst', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='invoicestorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceid', models.IntegerField(blank=True, null=True)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('deletorid', models.IntegerField(blank=True, null=True)),
                ('typeofchange', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('HSN', models.IntegerField()),
                ('tax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='quotationInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotationid', models.IntegerField()),
                ('customerid', models.IntegerField()),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('updatorid', models.IntegerField(blank=True, null=True)),
                ('customername', models.CharField(max_length=500)),
                ('customeraddress', models.CharField(blank=True, max_length=500, null=True)),
                ('customerpincode', models.CharField(blank=True, max_length=500, null=True)),
                ('customerstate', models.CharField(blank=True, max_length=500, null=True)),
                ('customergst', models.CharField(blank=True, max_length=500, null=True)),
                ('customerplaceofsupply', models.CharField(blank=True, max_length=500, null=True)),
                ('quotationdate', models.DateField()),
                ('terms', models.CharField(blank=True, max_length=500)),
                ('exiprydate', models.DateField()),
                ('quotationnumber', models.IntegerField()),
                ('items', jsonfield.fields.JSONField()),
                ('subtotalamount', models.FloatField(blank=True, null=True)),
                ('taxamount', models.FloatField(blank=True, null=True)),
                ('adjustmentamount', models.FloatField(blank=True, null=True)),
                ('finalamount', models.FloatField(blank=True, null=True)),
                ('signature', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='quotationstorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotationid', models.IntegerField(blank=True, null=True)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('deletorid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumbercounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='taxInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceid', models.IntegerField()),
                ('customerid', models.IntegerField()),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creatorname', models.CharField(blank=True, max_length=500, null=True)),
                ('updatorid', models.IntegerField(blank=True, null=True)),
                ('customername', models.CharField(max_length=500)),
                ('invoicedate', models.DateField(blank=True, null=True)),
                ('terms', models.CharField(blank=True, max_length=500)),
                ('duedate', models.DateField(blank=True, null=True)),
                ('po', models.CharField(blank=True, max_length=500)),
                ('items', jsonfield.fields.JSONField()),
                ('shippingState', models.CharField(blank=True, max_length=500)),
                ('subtotalamount', models.FloatField(blank=True, null=True)),
                ('taxamount', models.FloatField(blank=True, null=True)),
                ('adjustmentamount', models.FloatField(blank=True, null=True)),
                ('adjustmenttype', models.CharField(blank=True, max_length=500)),
                ('finalamount', models.FloatField(blank=True, null=True)),
                ('signature', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact mobile number', max_length=128, null=True, region=None)),
                ('nameofcontact', models.CharField(max_length=100)),
                ('contactparticulars', models.CharField(blank=True, max_length=100)),
                ('legalstatus', models.CharField(blank=True, choices=[('prlc', 'Private Limited Company'), ('pulc', 'Public Limited Company'), ('llp', 'Limited Liability Partnership'), ('partner', 'Partnership'), ('solepartner', 'Sole Proprietorship')], max_length=100)),
                ('gstno', models.CharField(blank=True, max_length=20)),
                ('cinno', models.CharField(blank=True, max_length=20)),
                ('panno', models.CharField(blank=True, max_length=20)),
                ('shopactno', models.CharField(blank=True, max_length=20)),
                ('businessgeography', models.CharField(blank=True, choices=[('gujrat', 'Inside Gujrat'), ('other', 'Outside Gujrat')], max_length=50)),
                ('marketsegment', models.CharField(blank=True, choices=[('medclg', 'Medical College'), ('pathological', 'Pathological Laboratories'), ('hospitals', 'Hospitals'), ('medpro', 'Medical Professionals'), ('sciclg', 'Science College'), ('schools', 'Schools'), ('rnd', 'R&D Institues'), ('agriculture', 'Agriculture'), ('veterinary', 'Veterinary'), ('industrial', 'Industrial')], max_length=50)),
                ('currentproducts', models.TextField(blank=True)),
                ('currentstaffstrength', models.IntegerField(blank=True, null=True)),
                ('customershandledsofar', models.TextField(blank=True)),
                ('salersturnover', models.IntegerField(blank=True, null=True)),
                ('parternshipcat', models.CharField(blank=True, choices=[('Level1', 'Level 1'), ('Level2', 'Level 2'), ('Level3', 'Level 3'), ('Level4', 'Level 4')], max_length=50)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=100)),
                ('distributer', models.CharField(max_length=500)),
                ('billingaddress', models.TextField()),
                ('billingcountry', models.CharField(max_length=50)),
                ('billingpincode', models.IntegerField()),
                ('billingcity', models.CharField(max_length=50)),
                ('billingstate', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.IntegerField(blank=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('stateid', models.IntegerField(null=True)),
                ('gst', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
