# Generated by Django 2.2.5 on 2020-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='customername',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
