# Generated by Django 2.2.5 on 2020-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_customerprofile_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customername',
            field=models.CharField(max_length=100),
        ),
    ]
