# Generated by Django 2.2.5 on 2020-03-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200305_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billingarea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billingbuilding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='billinglandmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='building',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
