# Generated by Django 2.2.5 on 2020-02-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200215_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsttable',
            name='cgst',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='gsttable',
            name='igst',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='gsttable',
            name='sgst',
            field=models.BooleanField(),
        ),
    ]
