# Generated by Django 2.2.5 on 2020-02-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200217_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinvoice',
            name='customeraddress',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='customergst',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='customerpincode',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='customerplaceofsupply',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='customerstate',
        ),
    ]
