# Generated by Django 2.2.5 on 2020-02-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200218_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='shippingState',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
