# Generated by Django 2.2.5 on 2020-03-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200315_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='area',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='billingarea',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='billingbuilding',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='billinglandmark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='building',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='landmark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
