# Generated by Django 2.2.5 on 2020-03-16 06:14

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200315_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinvoice',
            name='area',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='billingarea',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='billingbuilding',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='billinglandmark',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='building',
        ),
        migrations.RemoveField(
            model_name='taxinvoice',
            name='landmark',
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='customerdetails',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='customerid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='invoiceid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='items',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
