# Generated by Django 2.2.5 on 2020-02-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_taxinvoice_shippingstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='invoicedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
