# Generated by Django 2.2.5 on 2020-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200219_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='adjustmenttype',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
