# Generated by Django 3.0.3 on 2020-05-29 05:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='proformaInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceid', models.IntegerField(blank=True, null=True)),
                ('customerid', models.IntegerField(blank=True, null=True)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creatorname', models.CharField(blank=True, max_length=500, null=True)),
                ('updatorid', models.IntegerField(blank=True, null=True)),
                ('customername', models.CharField(max_length=500)),
                ('invoicedate', models.DateField(blank=True, null=True)),
                ('terms', models.CharField(blank=True, max_length=500)),
                ('po', models.CharField(blank=True, max_length=500, null=True)),
                ('items', jsonfield.fields.JSONField(blank=True, null=True)),
                ('customerdetails', jsonfield.fields.JSONField(blank=True, null=True)),
                ('finalamount', models.FloatField(blank=True, null=True)),
                ('signature', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
