# Generated by Django 2.2.5 on 2020-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_taxinvoice_adjustmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nameofcontact',
            field=models.CharField(max_length=100),
        ),
    ]
