# Generated by Django 2.2.5 on 2020-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200220_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='creatorname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
