# Generated by Django 3.0.3 on 2020-05-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_proformainvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='subtotalamount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='taxamount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
