# Generated by Django 2.2.5 on 2020-02-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_taxinvoice_creatorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicestorage',
            name='typeofchange',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
