# Generated by Django 3.0.3 on 2020-06-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_proformainvoice_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='shippingState',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
