# Generated by Django 3.0.3 on 2020-06-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20200617_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationinvoice',
            old_name='invoicedate',
            new_name='exiprydate',
        ),
        migrations.AddField(
            model_name='quotationinvoice',
            name='quotationdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
