# Generated by Django 3.0.3 on 2020-06-17 11:13

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200617_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challanid', models.IntegerField(blank=True, null=True)),
                ('customerid', models.IntegerField(blank=True, null=True)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creatorname', models.CharField(blank=True, max_length=500, null=True)),
                ('customername', models.CharField(max_length=500)),
                ('challandate', models.DateField(blank=True, null=True)),
                ('po', models.CharField(blank=True, max_length=500, null=True)),
                ('challannumber', models.CharField(blank=True, max_length=500, null=True)),
                ('items', jsonfield.fields.JSONField(blank=True, null=True)),
                ('customerdetails', jsonfield.fields.JSONField(blank=True, null=True)),
                ('shippingState', models.CharField(blank=True, max_length=500)),
                ('subtotalamount', models.FloatField(blank=True, null=True)),
                ('signature', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
