# Generated by Django 3.0.3 on 2020-06-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_deliverychallan'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryinvoicestorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challanid', models.IntegerField(blank=True, null=True)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('deletorid', models.IntegerField(blank=True, null=True)),
                ('typeofchange', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
