# Generated by Django 3.0.3 on 2020-06-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_installationinvoicestorage_installationreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installationreport',
            name='items',
        ),
        migrations.RemoveField(
            model_name='quotationinvoice',
            name='exiprydate',
        ),
    ]
